### ISSUE TITLE
Want 🐸TTS back

### ISSUE THREAD

**Issue by PicoUA** [robinhad/ukrainian-tts#26]
What happened? Why it's now working on ESPNET but not Coqui AI? The ESPNET models sound horrible and unrealistic.

**Comment by robinhad** [comment]
Hello stranger!
I would like to touch a couple of points that your question contains:
- I'm doing this project without pay in my free time, that I'd rather spend with my family and friends, instead of talking with demanding boys.
- As you may know, there are blackouts in Ukraine, which prevent me from training models till they reach desired quality. Coqui models were trained in summer, when there was a better situation with electricity. ESPNET ones were trained in October-December on my PC during frequent blackouts, so they are undertrained.
- Coqui models require 6 GB of dependencies for inference (ESPNET through ONNX require 100 MB), so it's bad for embedded devices, doesn't work on ARM, Coqui doesn't run on Windows, consumes 1.4x more RAM than ESPNET, uncustomizable, breaks on minor updates

If you would like to see a high-quality TTS (what does "horrible" even mean?), please put your money where your mouth is, donate here: https://send.monobank.ua/jar/48iHq4xAXm
just for your information: training run costs `$200` in cloud, consider that while donating.
